import {
  GPT_IMAGE_2_EDIT_MODEL_ID as MODEL_GPT_IMAGE_2_EDIT,
  GPT_IMAGE_2_TEXT_TO_IMAGE_MODEL_ID as MODEL_GPT_IMAGE_2_T2I,
  KLING_VIDEO_MODEL_ID as MODEL_KLING_TURBO,
  KLING_VIDEO_STANDARD_MODEL_ID as MODEL_KLING_STANDARD,
  KLING_VIDEO_PRO_MODEL_ID as MODEL_KLING_PRO,
  KLING_V3_VIDEO_MODEL_ID as MODEL_KLING_V3,
  KLING_V3_TEXT_TO_VIDEO_MODEL_ID as MODEL_KLING_V3_T2V,
  KLING_V3_IMAGE_TO_VIDEO_MODEL_ID as MODEL_KLING_V3_I2V,
  KLING_V3_CONTROL_VIDEO_MODEL_ID as MODEL_KLING_V3_CONTROL,
  KLING_O3_VIDEO_MODEL_ID as MODEL_KLING_O3_REF,
  KLING_O3_VIDEO_EDIT_MODEL_ID as MODEL_KLING_O3_EDIT,
  WAN_ANIMATE_REPLACE_MODEL_ID as MODEL_WAN_ANIMATE_REPLACE,
  WAN_ANIMATE_MODEL_ID as MODEL_WAN_ANIMATE,
  WAN_VISION_ENHANCER_MODEL_ID as MODEL_WAN_VISION,
  INFINITALK_VIDEO_MODEL_ID as MODEL_INFINITALK,
  WAN_27_VIDEO_MODEL_ID as MODEL_WAN_27_VIDEO,
  WAN_27_TEXT_TO_VIDEO_MODEL_ID as MODEL_WAN_27_T2V,
  WAN_27_IMAGE_TO_VIDEO_MODEL_ID as MODEL_WAN_27_I2V,
  WAN_27_REFERENCE_TO_VIDEO_MODEL_ID as MODEL_WAN_27_REF,
  WAN_27_EDIT_VIDEO_MODEL_ID as MODEL_WAN_27_EDIT,
  MINIMAX_H3_VIDEO_MODEL_ID as MODEL_MINIMAX_H3,
  MINIMAX_H3_TEXT_TO_VIDEO_MODEL_ID as MODEL_MINIMAX_H3_T2V,
  MINIMAX_H3_IMAGE_TO_VIDEO_MODEL_ID as MODEL_MINIMAX_H3_I2V,
  MINIMAX_H3_REFERENCE_TO_VIDEO_MODEL_ID as MODEL_MINIMAX_H3_REF,
  VEO_31_IMAGE_TO_VIDEO_MODEL_ID as MODEL_VEO_31_I2V,
  VEO_31_FFLF_VIDEO_MODEL_ID as MODEL_VEO_31_FFLF,
  VEO_31_EXTEND_VIDEO_MODEL_ID as MODEL_VEO_31_EXTEND,
  WAN_27_IMAGE_TEXT_TO_IMAGE_MODEL_ID as MODEL_WAN_27_T2I,
  WAN_27_IMAGE_IMAGE_TO_IMAGE_MODEL_ID as MODEL_WAN_27_I2I,
  SEEDANCE_15_VIDEO_MODEL_ID as MODEL_SEEDANCE_15,
  SEEDREAM_V5_PRO_MODEL_ID as MODEL_SEEDREAM_V5_PRO,
  SEEDREAM_V5_PRO_TEXT_TO_IMAGE_MODEL_ID as MODEL_SEEDREAM_V5_PRO_T2I,
  FAL_SEEDANCE_2_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL,
  FAL_SEEDANCE_2_TEXT_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_T2V,
  FAL_SEEDANCE_2_IMAGE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_I2V,
  FAL_SEEDANCE_2_REFERENCE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_REF,
  FAL_SEEDANCE_25_VIDEO_MODEL_ID as MODEL_SEEDANCE_25_FAL,
  FAL_SEEDANCE_25_TEXT_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_25_FAL_T2V,
  FAL_SEEDANCE_25_IMAGE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_25_FAL_I2V,
  FAL_SEEDANCE_25_REFERENCE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_25_FAL_REF,
  HEYGEN_V3_LIPSYNC_MODEL_ID as MODEL_HEYGEN_V3_LIPSYNC,
  KREA_2_LARGE_TEXT_TO_IMAGE_MODEL_ID as MODEL_KREA_2_LARGE,
} from '../modelConfig'; // Canonical model IDs.

export const GPT_IMAGE_2_EDIT_MODEL_ID = MODEL_GPT_IMAGE_2_EDIT; // GPT Image 2 edit endpoint.
export const GPT_IMAGE_2_TEXT_TO_IMAGE_MODEL_ID = MODEL_GPT_IMAGE_2_T2I; // GPT Image 2 t2i endpoint.
export const KREA_2_LARGE_TEXT_TO_IMAGE_MODEL_ID = MODEL_KREA_2_LARGE; // Krea 2 Large t2i endpoint.

export const KLING_IMAGE_TO_VIDEO_MODEL_ID = MODEL_KLING_TURBO; // Kling turbo endpoint.
export const KLING_IMAGE_TO_VIDEO_STANDARD_MODEL_ID = MODEL_KLING_STANDARD; // Kling standard endpoint.
export const KLING_IMAGE_TO_VIDEO_PRO_MODEL_ID = MODEL_KLING_PRO; // Kling pro endpoint.
export const KLING_V3_VIDEO_MODEL_ID = MODEL_KLING_V3; // Kling v3 smart selector.
export const KLING_V3_TEXT_TO_VIDEO_MODEL_ID = MODEL_KLING_V3_T2V; // Kling v3 text endpoint.
export const KLING_V3_IMAGE_TO_VIDEO_MODEL_ID = MODEL_KLING_V3_I2V; // Kling v3 image endpoint.
export const KLING_V3_CONTROL_VIDEO_MODEL_ID = MODEL_KLING_V3_CONTROL; // Kling v3 Control endpoint.

export const KLING_O3_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_KLING_O3_REF; // Kling O3 reference endpoint.
export const KLING_O3_VIDEO_EDIT_MODEL_ID = MODEL_KLING_O3_EDIT; // Kling O3 edit endpoint.

export const WAN_ANIMATE_REPLACE_MODEL_ID = MODEL_WAN_ANIMATE_REPLACE; // Wan animate replace endpoint.
export const WAN_ANIMATE_MODEL_ID = MODEL_WAN_ANIMATE; // Wan animate alias.
export const WAN_VISION_ENHANCER_MODEL_ID = MODEL_WAN_VISION; // Wan vision enhancer endpoint.
export const INFINITALK_VIDEO_MODEL_ID = MODEL_INFINITALK; // Infinitalk endpoint.
export const WAN_27_VIDEO_MODEL_ID = MODEL_WAN_27_VIDEO; // Wan 2.7 smart video selector.
export const WAN_27_TEXT_TO_VIDEO_MODEL_ID = MODEL_WAN_27_T2V; // Wan 2.7 text-to-video endpoint.
export const WAN_27_IMAGE_TO_VIDEO_MODEL_ID = MODEL_WAN_27_I2V; // Wan 2.7 image-to-video endpoint.
export const WAN_27_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_WAN_27_REF; // Wan 2.7 reference endpoint.
export const WAN_27_EDIT_VIDEO_MODEL_ID = MODEL_WAN_27_EDIT; // Wan 2.7 edit-video endpoint.
export const MINIMAX_H3_VIDEO_MODEL_ID = MODEL_MINIMAX_H3; // MiniMax H3 selector.
export const MINIMAX_H3_TEXT_TO_VIDEO_MODEL_ID = MODEL_MINIMAX_H3_T2V; // MiniMax H3 text endpoint.
export const MINIMAX_H3_IMAGE_TO_VIDEO_MODEL_ID = MODEL_MINIMAX_H3_I2V; // MiniMax H3 image endpoint.
export const MINIMAX_H3_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_MINIMAX_H3_REF; // MiniMax H3 reference endpoint.
export const VEO_31_IMAGE_TO_VIDEO_MODEL_ID = MODEL_VEO_31_I2V; // Veo 3.1 image-to-video endpoint.
export const VEO_31_FFLF_VIDEO_MODEL_ID = MODEL_VEO_31_FFLF; // Veo 3.1 fflf endpoint.
export const VEO_31_EXTEND_VIDEO_MODEL_ID = MODEL_VEO_31_EXTEND; // Veo 3.1 extend endpoint.
export const WAN_27_IMAGE_TEXT_TO_IMAGE_MODEL_ID = MODEL_WAN_27_T2I; // Wan 2.7 Pro text-to-image endpoint.
export const WAN_27_IMAGE_IMAGE_TO_IMAGE_MODEL_ID = MODEL_WAN_27_I2I; // Wan 2.7 Pro edit endpoint.
export const HEYGEN_V3_LIPSYNC_MODEL_ID = MODEL_HEYGEN_V3_LIPSYNC; // HeyGen v3 lipsync endpoint.
export const SEEDANCE_15_VIDEO_MODEL_ID = MODEL_SEEDANCE_15; // Seedance 1.5 endpoint.
export const SEEDREAM_V5_PRO_MODEL_ID = MODEL_SEEDREAM_V5_PRO; // Seedream 5 Pro edit endpoint.
export const SEEDREAM_V5_PRO_TEXT_TO_IMAGE_MODEL_ID = MODEL_SEEDREAM_V5_PRO_T2I; // Seedream 5 Pro t2i endpoint.
export const FAL_SEEDANCE_2_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL; // Fal Seedance 2 selector.
export const FAL_SEEDANCE_2_TEXT_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_T2V; // Fal Seedance 2 t2v endpoint.
export const FAL_SEEDANCE_2_IMAGE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_I2V; // Fal Seedance 2 i2v endpoint.
export const FAL_SEEDANCE_2_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_REF; // Fal Seedance 2 reference endpoint.
export const FAL_SEEDANCE_25_VIDEO_MODEL_ID = MODEL_SEEDANCE_25_FAL; // Fal Seedance 2.5 selector.
export const FAL_SEEDANCE_25_TEXT_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_25_FAL_T2V; // Fal Seedance 2.5 t2v endpoint.
export const FAL_SEEDANCE_25_IMAGE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_25_FAL_I2V; // Fal Seedance 2.5 i2v endpoint.
export const FAL_SEEDANCE_25_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_25_FAL_REF; // Fal Seedance 2.5 reference endpoint.
