import {
  HAILUO_IMAGE_TO_VIDEO_STANDARD_MODEL_ID as MODEL_HAILUO_STANDARD,
  HAILUO_IMAGE_TO_VIDEO_PRO_MODEL_ID as MODEL_HAILUO_PRO,
  KLING_VIDEO_MODEL_ID as MODEL_KLING_TURBO,
  KLING_VIDEO_STANDARD_MODEL_ID as MODEL_KLING_STANDARD,
  KLING_VIDEO_PRO_MODEL_ID as MODEL_KLING_PRO,
  KLING_26_VIDEO_MODEL_ID as MODEL_KLING_26,
  KLING_O1_VIDEO_MODEL_ID as MODEL_KLING_O1_REF,
  KLING_O1_VIDEO_EDIT_MODEL_ID as MODEL_KLING_O1_EDIT,
  KLING_O1_VIDEO_REF_V2V_MODEL_ID as MODEL_KLING_O1_REFV2V,
  KLING_O1_VIDEO_FFLF_MODEL_ID as MODEL_KLING_O1_FFLF,
  WAN_ANIMATE_REPLACE_MODEL_ID as MODEL_WAN_ANIMATE_REPLACE,
  WAN_ANIMATE_MODEL_ID as MODEL_WAN_ANIMATE,
  WAN_VISION_ENHANCER_MODEL_ID as MODEL_WAN_VISION,
  INFINITALK_VIDEO_MODEL_ID as MODEL_INFINITALK,
  WAN_26_I2V_MODEL_ID as MODEL_WAN_26_I2V,
  VEO_31_IMAGE_TO_VIDEO_MODEL_ID as MODEL_VEO_31_I2V,
  VEO_31_FFLF_VIDEO_MODEL_ID as MODEL_VEO_31_FFLF,
  VEO_31_EXTEND_VIDEO_MODEL_ID as MODEL_VEO_31_EXTEND,
  WAN_27_IMAGE_TEXT_TO_IMAGE_MODEL_ID as MODEL_WAN_27_T2I,
  WAN_27_IMAGE_IMAGE_TO_IMAGE_MODEL_ID as MODEL_WAN_27_I2I,
  SEEDANCE_15_VIDEO_MODEL_ID as MODEL_SEEDANCE_15,
  FAL_SEEDANCE_2_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL,
  FAL_SEEDANCE_2_TEXT_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_T2V,
  FAL_SEEDANCE_2_IMAGE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_I2V,
  FAL_SEEDANCE_2_REFERENCE_TO_VIDEO_MODEL_ID as MODEL_SEEDANCE_2_FAL_REF,
  HEYGEN_V3_LIPSYNC_MODEL_ID as MODEL_HEYGEN_V3_LIPSYNC,
} from '../modelConfig'; // Canonical model IDs.

export const HAILUO_IMAGE_TO_VIDEO_STANDARD_MODEL_ID = MODEL_HAILUO_STANDARD; // Hailuo standard endpoint.
export const HAILUO_IMAGE_TO_VIDEO_PRO_MODEL_ID = MODEL_HAILUO_PRO; // Hailuo pro endpoint.
export const HAILUO_IMAGE_TO_VIDEO_MODEL_ID = MODEL_HAILUO_PRO; // Default to pro for Fal service.

export const KLING_IMAGE_TO_VIDEO_MODEL_ID = MODEL_KLING_TURBO; // Kling turbo endpoint.
export const KLING_IMAGE_TO_VIDEO_STANDARD_MODEL_ID = MODEL_KLING_STANDARD; // Kling standard endpoint.
export const KLING_IMAGE_TO_VIDEO_PRO_MODEL_ID = MODEL_KLING_PRO; // Kling pro endpoint.
export const KLING_26_IMAGE_TO_VIDEO_MODEL_ID = MODEL_KLING_26; // Kling 2.6 endpoint.

export const KLING_O1_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_KLING_O1_REF; // Kling O1 reference endpoint.
export const KLING_O1_VIDEO_EDIT_MODEL_ID = MODEL_KLING_O1_EDIT; // Kling O1 edit endpoint.
export const KLING_O1_VIDEO_REF_V2V_MODEL_ID = MODEL_KLING_O1_REFV2V; // Kling O1 ref-v2v endpoint.
export const KLING_O1_VIDEO_FFLF_MODEL_ID = MODEL_KLING_O1_FFLF; // Kling O1 fflf endpoint.

export const WAN_ANIMATE_REPLACE_MODEL_ID = MODEL_WAN_ANIMATE_REPLACE; // Wan animate replace endpoint.
export const WAN_ANIMATE_MODEL_ID = MODEL_WAN_ANIMATE; // Wan animate alias.
export const WAN_VISION_ENHANCER_MODEL_ID = MODEL_WAN_VISION; // Wan vision enhancer endpoint.
export const INFINITALK_VIDEO_MODEL_ID = MODEL_INFINITALK; // Infinitalk endpoint.
export const WAN_26_I2V_MODEL_ID = MODEL_WAN_26_I2V; // Wan 2.6 image-to-video endpoint.
export const VEO_31_IMAGE_TO_VIDEO_MODEL_ID = MODEL_VEO_31_I2V; // Veo 3.1 image-to-video endpoint.
export const VEO_31_FFLF_VIDEO_MODEL_ID = MODEL_VEO_31_FFLF; // Veo 3.1 fflf endpoint.
export const VEO_31_EXTEND_VIDEO_MODEL_ID = MODEL_VEO_31_EXTEND; // Veo 3.1 extend endpoint.
export const WAN_27_IMAGE_TEXT_TO_IMAGE_MODEL_ID = MODEL_WAN_27_T2I; // Wan 2.7 Pro text-to-image endpoint.
export const WAN_27_IMAGE_IMAGE_TO_IMAGE_MODEL_ID = MODEL_WAN_27_I2I; // Wan 2.7 Pro edit endpoint.
export const HEYGEN_V3_LIPSYNC_MODEL_ID = MODEL_HEYGEN_V3_LIPSYNC; // HeyGen v3 lipsync endpoint.
export const SEEDANCE_15_VIDEO_MODEL_ID = MODEL_SEEDANCE_15; // Seedance 1.5 endpoint.
export const FAL_SEEDANCE_2_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL; // Fal Seedance 2 selector.
export const FAL_SEEDANCE_2_TEXT_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_T2V; // Fal Seedance 2 t2v endpoint.
export const FAL_SEEDANCE_2_IMAGE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_I2V; // Fal Seedance 2 i2v endpoint.
export const FAL_SEEDANCE_2_REFERENCE_TO_VIDEO_MODEL_ID = MODEL_SEEDANCE_2_FAL_REF; // Fal Seedance 2 reference endpoint.
