export const CROP_HANDLE_SIZE = 10;
export const TRANSFORM_HANDLE_SIZE = 10;
export const ROTATION_HANDLE_DISTANCE = 30;
// Note anchor pins render at constant screen size (divide by scale for world units).
export const NOTE_PIN_HEAD_RADIUS = 12;
export const NOTE_PIN_HEAD_OFFSET = 22; // Screen px from the anchor tip up to the head center.
export const NOTE_PIN_LABEL_FONT_SIZE = 12;
export const NOTE_PIN_FILL = '#0ea5e9';
export const NOTE_PIN_BORDER = '#f8fafc';
export const MIN_SCALE = 0.001; // allow zooming far out to keep huge layouts visible
export const MAX_SCALE = 10;
export const GRID_BASE_SIZE = 300;
export const GRID_MIN_SIZE = 2;
export const GRID_MAX_SIZE = 360;
export const GRID_VISUAL_SCALE = 0.6; // Makes the grid look about 40% more zoomed out than the original default.
export const DOT_BASE_SIZE = 3.5;
export const DOT_MIN_SIZE = 0.4;
export const DOT_MAX_SIZE = 6;
export const KEYBOARD_ZOOM_MULTIPLIER = 1.05; // 5% zoom steps for keyboard shortcuts
export const KEYBOARD_ZOOM_OUT_MULTIPLIER = 1 / KEYBOARD_ZOOM_MULTIPLIER;
export const WHEEL_ZOOM_MULTIPLIER = 1.1;
export const MIN_STROKE_SIZE = 1;
export const MAX_STROKE_SIZE = 100;
export const KEYBOARD_STROKE_STEP = 1;
