export const RESIZE_HANDLE_SIZE = 12;
export const CROP_HANDLE_SIZE = 10;
export const TRANSFORM_HANDLE_SIZE = 10;
export const ROTATION_HANDLE_DISTANCE = 30;
export const MIN_NOTE_WIDTH = 100;
export const MIN_NOTE_HEIGHT = 50;
export const DEFAULT_NOTE_FONT_SIZE = 16;
export const MIN_NOTE_FONT_SIZE = 8;
export const MAX_NOTE_FONT_SIZE = 72;
export const MIN_SCALE = 0.001; // allow zooming far out to keep huge layouts visible
export const MAX_SCALE = 10;
export const GRID_BASE_SIZE = 300;
export const GRID_MIN_SIZE = 2;
export const GRID_MAX_SIZE = 360;
export const GRID_VISUAL_SCALE = 0.6; // Makes the grid look about 40% more zoomed out than the original default.
export const DOT_BASE_SIZE = 3.5;
export const DOT_MIN_SIZE = 0.4;
export const DOT_MAX_SIZE = 6;
export const KEYBOARD_ZOOM_MULTIPLIER = 1.05; // 5% zoom steps for keyboard shortcuts
export const KEYBOARD_ZOOM_OUT_MULTIPLIER = 1 / KEYBOARD_ZOOM_MULTIPLIER;
export const WHEEL_ZOOM_MULTIPLIER = 1.1;
export const MIN_STROKE_SIZE = 1;
export const MAX_STROKE_SIZE = 100;
export const KEYBOARD_STROKE_STEP = 1;
