import { FaMousePointer, FaHandPaper, FaPencilAlt, FaMagic, FaUndo, FaRedo, FaDownload, FaTrash, FaExpandAlt, FaStickyNote, FaArrowUp, FaArrowDown, FaEraser, FaCropAlt, FaCheck, FaTimes } from 'react-icons/fa';
import { IoNuclear } from 'react-icons/io5';
import { RxCursorArrow } from 'react-icons/rx';

export const SelectionIcon = FaMousePointer;
export const PanIcon = FaHandPaper;
export const FreeSelectionIcon = RxCursorArrow;
export const AnnotateIcon = FaPencilAlt;
export const InpaintIcon = FaMagic;
export const EraseIcon = FaEraser;
export const NoteIcon = FaStickyNote;
export const CropIcon = FaCropAlt;
export const ClearIcon = IoNuclear;
export const UndoIcon = FaUndo;
export const RedoIcon = FaRedo;
export const DownloadIcon = FaDownload;
export const DeleteIcon = FaTrash;
export const ZoomToFitIcon = FaExpandAlt;
export const LayerUpIcon = FaArrowUp;
export const LayerDownIcon = FaArrowDown;
export const ConfirmIcon = FaCheck;
export const CancelIcon = FaTimes;