import React from 'react';
import { FaMousePointer, FaHandPaper, FaPencilAlt, FaUndo, FaRedo, FaDownload, FaTrash, FaExpandAlt, FaStickyNote, FaArrowUp, FaArrowDown, FaEraser, FaCropAlt, FaCheck, FaTimes, FaCopy, FaPaintBrush, FaChevronDown, FaUpload, FaBars, FaInfoCircle, FaExpand, FaSyncAlt, FaRulerCombined, FaRegClone, FaPlay, FaPause, FaCamera, FaMicrophone, FaStop, FaUserSecret, FaCrosshairs, FaPlus, FaMinus, FaRobot, FaHistory, FaThumbtack, FaFolder, FaFolderPlus, FaEllipsisV, FaMapMarkerAlt } from 'react-icons/fa';
import { RiCameraLensLine } from 'react-icons/ri';
import { PiSelectionBold } from 'react-icons/pi';
import { IoNuclear, IoSparkles } from 'react-icons/io5';
import { RxCursorArrow, RxFontSize } from 'react-icons/rx';
import type { IconBaseProps } from 'react-icons';

// Extend IconBaseProps to include className
interface IconProps extends IconBaseProps {
  className?: string;
}

export const SelectionIcon = FaMousePointer as React.FC<IconProps>;
export const PanIcon = FaHandPaper as React.FC<IconProps>;
export const FreeSelectionIcon = RxCursorArrow as React.FC<IconProps>;
export const AnnotateIcon = FaPencilAlt as React.FC<IconProps>;
export const EraseIcon = FaEraser as React.FC<IconProps>;
export const NoteIcon = FaStickyNote as React.FC<IconProps>;
export const BrushIcon = FaPaintBrush as React.FC<IconProps>;
export const CropIcon = FaCropAlt as React.FC<IconProps>;
export const ClearIcon = IoNuclear as React.FC<IconProps>;
export const UndoIcon = FaUndo as React.FC<IconProps>;
export const RedoIcon = FaRedo as React.FC<IconProps>;
export const DownloadIcon = FaDownload as React.FC<IconProps>;
export const DeleteIcon = FaTrash as React.FC<IconProps>;
export const ZoomToFitIcon = FaExpandAlt as React.FC<IconProps>;
export const LayerUpIcon = FaArrowUp as React.FC<IconProps>;
export const LayerDownIcon = FaArrowDown as React.FC<IconProps>;
export const ConfirmIcon = FaCheck as React.FC<IconProps>;
export const CancelIcon = FaTimes as React.FC<IconProps>;
export const CopyIcon = FaCopy as React.FC<IconProps>;
export const ChevronDownIcon = FaChevronDown as React.FC<IconProps>;
export const PinIcon = FaThumbtack as React.FC<IconProps>;
export const FolderIcon = FaFolder as React.FC<IconProps>;
export const NewFolderIcon = FaFolderPlus as React.FC<IconProps>;
export const KebabIcon = FaEllipsisV as React.FC<IconProps>;
export const RenameIcon = FaPencilAlt as React.FC<IconProps>;
export const RemoveBackgroundIcon = IoSparkles as React.FC<IconProps>;
export const UploadIcon = FaUpload as React.FC<IconProps>;
export const HamburgerIcon = FaBars as React.FC<IconProps>;
export const MetadataIcon = FaInfoCircle as React.FC<IconProps>;
export const TransformIcon = FaExpand as React.FC<IconProps>;
export const RerunIcon = FaSyncAlt as React.FC<IconProps>;
export const ResizeIcon = FaRulerCombined as React.FC<IconProps>;
export const DuplicateIcon = FaRegClone as React.FC<IconProps>;
export const PlayIcon = FaPlay as React.FC<IconProps>;
export const PauseIcon = FaPause as React.FC<IconProps>;
export const SnapshotIcon = FaCamera as React.FC<IconProps>;
export const CameraSettingsIcon = RiCameraLensLine as React.FC<IconProps>;
export const MicrophoneIcon = FaMicrophone as React.FC<IconProps>;
export const StopIcon = FaStop as React.FC<IconProps>;
export const BlindTestIcon = FaUserSecret as React.FC<IconProps>;
export const CrosshairIcon = FaCrosshairs as React.FC<IconProps>;
export const VideoPromptAreaIcon = PiSelectionBold as React.FC<IconProps>;
export const PlusIcon = FaPlus as React.FC<IconProps>;
export const MinusIcon = FaMinus as React.FC<IconProps>;
export const RobotIcon = FaRobot as React.FC<IconProps>;
export const MapPinIcon = FaMapMarkerAlt as React.FC<IconProps>;
export const HistoryIcon = FaHistory as React.FC<IconProps>;
export const FontSizeIcon = RxFontSize as React.FC<IconProps>;
